# TL;DR: YOU SHOULD DELETE THIS FILE
#
# This file was generated by Cucumber-Rails and is only here to get you a head start
# These step definitions are thin wrappers around the Capybara/Webrat API that lets you
# visit pages, interact with widgets and make assertions about page content.
#
# If you use these step definitions as basis for your features you will quickly end up
# with features that are:
#
# * Hard to maintain
# * Verbose to read
#
# A much better approach is to write your own higher level step definitions, following
# the advice in the following blog posts:
#
# * http://benmabey.com/2008/05/19/imperative-vs-declarative-scenarios-in-user-stories.html
# * http://dannorth.net/2011/01/31/whose-domain-is-it-anyway/
# * http://elabs.se/blog/15-you-re-cuking-it-wrong
#


require 'uri'
require 'cgi'
require File.expand_path(File.join(File.dirname(__FILE__), "..", "support", "paths"))
require File.expand_path(File.join(File.dirname(__FILE__), "..", "support", "selectors"))

module WithinHelpers
  def with_scope(locator)
    locator ? within(*selector_for(locator)) { yield } : yield
  end
end
World(WithinHelpers)


Given(/^I am on the home page$/) do
  visit "/"
end

Given(/^I am on the cursos page$/) do
  visit "/cursos"
end


Then(/^I should fill in "([^"]*)" with "([^"]*)"$/) do |campo, valor|
  fill_in(campo, :with => valor)
end

Then(/^I submit$/) do
	page.should have_selector("input[type=submit][value='Entrar']")
	page.find("input[type=submit][value='Entrar']").click
	sleep(0.25)

end

Then(/^I should read in "([^"]*)" the string "([^"]*)"$/) do |campo, valor|
  expect(find_field(campo).value).to eq valor
end


Given(/^I am logged in with "([^"]*)" and "([^"]*)" as values$/) do |login, password|
  	fill_in("nome", :with => login)
  	fill_in("senha", :with => password)
	page.find("input[type=submit][value='Entrar']").click
	sleep(0.25)
end

Then(/^I click in "([^"]*)"$/) do |arg1|
  find_link(arg1).click
  sleep(0.25)
end


Then(/^i should not see "([^"]*)"$/) do |entrada|
  page.should have_no_selector(entrada)
end




Then(/^I should be in "([^"]*)"$/) do |pagina|
  expect(current_path).to eq pagina
end


Given(/^I am on the Disciplinas page$/) do
  visit '/disciplinas'
end

Then(/^I should see "([^"]*)" as a element$/) do |codigo|
  page.all(codigo)
end

Then(/^I insert "([^"]*)" as nome, "([^"]*)" as codigo, "([^"]*)" as titulo, "([^"]*)" as credito$/) do |nome, codigo, titulo, credito|
   	fill_in("curso_nome", :with => nome)
   	fill_in("curso_codigo", :with => codigo)
   	fill_in("curso_titulo", :with => titulo)
   	fill_in("curso_creditos", :with => credito)
end

Then(/^I submit the curso$/) do
  	page.find("input[type=submit][value='Adicionar curso']").click
	sleep(0.25)
end
